### ISSUE TITLE
Create centralized location for configuration 

### ISSUE THREAD

**Issue by ryanw-se** [tnws/kira#1]
I noticed how there is an API text file for one token, but others are scattered throughout the project. it would be pretty handy to provide a centralized location for people to add API tokens for all of the 3rd party features they wish to use with Kira.

**Comment by tnws** [comment]
Sounds like a good idea to me. Probably a JSON though, unless anyone has any other suggestions.

**Comment by gilrosenthal** [comment]
I made a pull request #2  to try and fix this
